### PR TITLE
Change do-not-edit header to the official one

### PR DESCRIPTION
**Pull request by gonzaloserrano**
The new format is what other tools like gqlgen does.

This is need to make tools like golint ignore it.

See https://github.com/golang/go/issues/13560#issuecomment-288457920

### CODE REVIEW

**Comment by gonzaloserrano** [comment]
*reminder*

**Comment by atombender** [comment]
Sorry about the delay. Thanks for the PR!

**Comment by gonzaloserrano** [comment]
Thank you. Would you mind tagging a new version?

**Comment by atombender** [comment]
Done!

**Pull request merged**
