### PR TITLE
Add support for $id keyword

### PR DESCRIPTION
**Pull request by vaihtovirta**
Hello!
In my project, I'm working with json schemas that use the `$id`  keyword introduced in [draft-wright-json-schema-01](https://tools.ietf.org/html/draft-wright-json-schema-01#appendix-B).
To make schema mapping working, I've introduced the `Schema#ID()` method, which allows us to work with both `id` and `$id` keywords.

### CODE REVIEW

**Comment by atombender** [comment]
Do you have to work with both? Why not just assume `$id`, then add an internal field mapped to `id`, and some unmarshalling code that migrates it if it exists?

**Comment by vaihtovirta** [comment]
We only have schemas with `$id`, so there is no need to work with both simultaneously.
By the custom unmarshalling did you mean something like this:

```go
type Schema struct {
	ID          string      `json:"$id"` // RFC draft-wright-json-schema-01, section-9.2
	LegacyID    string      `json:"id"`  // RFC draft-wright-json-schema-00, section 4.5
	Definitions Definitions `json:"definitions,omitempty"`
}

func (s *Schema) UnmarshalJSON(data []byte) error {
	var tempSch tempSchema
	if err := json.Unmarshal(data, &tempSch); err != nil {
		return err
	}

	if tempSch.ID == "" {
		tempSch.ID = tempSch.LegacyID
	}

	*s = tempSch.getSchema()

	return nil
}

type tempSchema Schema

func (ts *tempSchema) getSchema() Schema {
	return Schema{
		ID:          ts.ID,
		Definitions: ts.Definitions,
	}
}
````

**Comment by atombender** [comment]
Yes, exactly.

**Comment by vaihtovirta** [comment]
Cool, I'll update the PR 👌

**Review by atombender — APPROVED** [review]

**Comment by atombender** [comment]
Thanks!

**Comment by ziposcar** [comment]
This PR is so helpful. Is it ready to be merged?

**Comment by atombender** [comment]
@ziposcar @vaihtovirta Sorry about the lateness, kind of dropped the ball on this! Merged now.

**Pull request merged**
