### PR TITLE
Accept boolean value for a JSON Schema

### PR DESCRIPTION
**Pull request by au-phiware**
Prior to this change, additionalItems and additionalProperties only accepted an object.  The spec also allows boolean values for these properties and indeed any field that expects a JSON Schema.
See these [release notes][1].

This change introduces the ObjectAsType struct.  This struct is an alias of Type, which now satisfies the json.Unmarshaler interface, that can now be unmarshalled from either a bool or object.  A boolean value of `true` is equivalent to an empty Schema, whereas `false` is the opposite (i.e. `not` an empty Schema).

[1]: https://json-schema.org/draft-06/json-schema-release-notes.html#additions-and-backwards-compatible-changes

### CODE REVIEW

**Comment by bohlander** [comment]
I ran into this issue as well. Would be great to see this fix merged! In meantime I'm working around by rewriting `additionalProperties` from `false` -> `null`.

**Comment by au-phiware** [comment]
> I ran into this issue as well. Would be great to see this fix merged! In meantime I'm working around by rewriting `additionalProperties` from `false` -> `null`.

Tread lightly @bohlander, IIRC `null` gets interpreted as `true` or the empty type (`{}`).  I think you want this: `{"not":{}}`.  (Which makes for some interesting validation messages from some validators.)

**Comment by tjungblu** [comment]
any chances we can get that merged? We would also love to use that in our schema generation.

**Comment by atombender** [comment]
Thanks!

**Comment by jdimeo** [comment]
This one bit me hard- thank you so much for doing this!

**Pull request merged**
